[package]
name = 'seta'
version = '0.1.0'
authors = ['Zain Aamer <ZippeyKeys12@gmail.com>']
edition = '2018'

[dependencies]
clap = '2.33.0'
console = '0.9.2'
indicatif = '0.14.0'
dialoguer = '0.5.0'
lazy_static = '1.4.0'
rayon = '1.3.0'
regex = '1.3.4'
json = '0.12.1'
yaml-rust = '0.4.3'
toml = '0.5.6'
nom = '5.1.1'
llvm-sys = '90.0.0'
