[package]
name = 'seta'
version = '0.1.0'
authors = ['Zain Aamer <ZippeyKeys12@gmail.com>']
edition = '2018'

[dependencies]
clap = '2.33.0'
lazy_static = '1.4.0'
rayon = '1.3.0'
regex = '1.3.4'
toml = '0.5.6'
nom = '5.1.1'

[dependencies.inkwell]
git = 'https://github.com/TheDan64/inkwell'
branch = 'master'
features = ['llvm9-0']
